name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name:  Clean
        run: |
          rm dist/css/*
          
      - name:  Install dev dependancies
        run: |
          npm install
          npx browserslist@latest --update-db
      - name: Compile CSS
        run:
          npm run sass:build

      - name:  Clean
        run: |
          rm -r node_modules
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Dist
