name: Pleeease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use NodeJS
      uses: actions/setup-node@v2.1.4
    
    - name: Pleeease
      run:
        npm install -g pleeease-cli
        pleeease compile
