name: Pleeease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: install
        run: npm install -g pleeease-cli
      
      - name: Run
        run: pleeease compile
