name: Pleeease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      uses: actions/setup-node@v2.1.4
    - run: npm install -g pleeease-cli
    - run: pleeease compile
