name: Pleeease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: install sass
        run:
          sudo chown -R $USER /usr/local/lib/node_modules
          npm install -g sass

      - name: install sass
        run:
          sass sass:dist/css

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sass build
